# Generated by Django 5.2.3 on 2024-07-26 12:00

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    User = apps.get_model('users', 'User') # Get our custom user model

    # Create Admin Group
    admin_group, created = Group.objects.get_or_create(name='admin')
    if created:
        # Assign all permissions to admin group
        all_permissions = Permission.objects.all()
        admin_group.permissions.set(all_permissions)
        print("Created 'admin' group and assigned all permissions.")

    # Create Tour Operator Group
    tour_operator_group, created = Group.objects.get_or_create(name='tour_operator')
    if created:
        # Example: Assign permission to view users.
        # In a real scenario, you'd assign permissions related to a 'Tour' model.
        try:
            user_content_type = ContentType.objects.get_for_model(User)
            view_user_permission = Permission.objects.get(
                codename='view_user',
                content_type=user_content_type,
            )
            tour_operator_group.permissions.add(view_user_permission)
            print("Created 'tour_operator' group and assigned 'view_user' permission.")
        except ContentType.DoesNotExist:
            print("ContentType for User model not found. Skipping 'view_user' permission for 'tour_operator' group.")
        except Permission.DoesNotExist:
            print("'view_user' permission not found. Skipping 'view_user' permission for 'tour_operator' group.")


def revert_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['admin', 'tour_operator']).delete()
    print("Deleted 'admin' and 'tour_operator' groups.")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'), # Ensure this depends on the initial user migration
        # It's also good practice to depend on the creation of permissions
        ('auth', '0012_alter_user_first_name_max_length'), # or the latest auth migration that creates permissions
        ('contenttypes', '0002_remove_content_type_name'), # and contenttypes
    ]

    operations = [
        migrations.RunPython(create_groups, revert_groups),
    ]
