# Generated by Django 5.2.3 on 2025-06-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tourbooking_tour_travelers'),
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='tours',
            field=models.ManyToManyField(related_name='booked_travelers', through='tour.TourBooking', to='tour.tour'),
        ),
    ]
