# Generated by Django 5.2.3 on 2025-06-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending_payment', 'Pending Payment'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted')], default='pending_payment', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('room_configuration', models.TextField(blank=True, help_text='e.g., Single Room, Double shared with Jane Doe', null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.tour')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_bookings', to='traveler.traveler')),
            ],
            options={
                'verbose_name': 'Tour Booking',
                'verbose_name_plural': 'Tour Bookings',
                'ordering': ['-booking_date'],
                'unique_together': {('tour', 'traveler')},
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='travelers',
            field=models.ManyToManyField(related_name='booked_tours', through='tour.TourBooking', to='traveler.traveler'),
        ),
    ]
